### ISSUE TITLE
build-profile not used

### ISSUE THREAD

**Issue by ocpmax** [OCamlPro/drom#110]
For the js skeletons, we need to set the build-profile to "release" because it changes the js_of_ocaml compiling behaviour (there is no other method to do this in dune).
The build-profile should be propagated to at least the Makefile to do `dune build --profile <build-profile>`

**Comment by lefessan** [comment]
If I remember well, the problem is mostly a reference to `VueRouter` that is missing. Wouldn't it be possible to create a dummy reference to this module, so that it always gets included ? That way, there would be no need for compiling in release mode ? (though it is still useful to have such a patch for other reasons)
