### ISSUE TITLE
Add support for "skip" in package.toml

### ISSUE THREAD

**Issue by ddeclerck** [OCamlPro/drom#131]
At the moment, "skip" is only supported in drom.toml.
It would be useful to also have it in package.toml (possibly with paths relative to the directory containing the .toml file).

**Comment by lefessan** [comment]
Done in #133 with relative paths to the directory containing the drom.toml file.
Note that `drom package --skip X` will add `A` into the project skip list, not the package skip list, because the option is a project option. I am worried of changing the semantics of this option for the `package` command only.
