### ISSUE TITLE
Error with Toml library

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/drom#134]
@zapashcanon There is a problem everytime the `package.toml` file is saved, a newline is added to every multi-line string field starting with """. 

See https://github.com/OCamlPro/freeton-ocaml-sdk/blob/e647f5740ac995ba92a844280fcb8f5ba8cba57f/src/ft_lib/package.toml#L58 for example. 

This problem was not there before the last change in the Toml library.

**Comment by zapashcanon** [comment]
@lefessan can you test with the master branch of toml ? IIRC the problem was in the code you wrote for the multi-line support and I fixed it in [this commit](https://github.com/ocaml-toml/To.ml/commit/2dc7e75dce4459666bb5d2d8edf0a68b287bc593). If you can confirm this is fixed, I'll do a new release of toml.

**Comment by lefessan** [comment]
I am quite busy at the time. Since you have access to both source codes, it will be faster if you can test it directly.
