### ISSUE TITLE
warning when using drom globally

### ISSUE THREAD

**Issue by joprice** [OCamlPro/drom#150]
I get the following warning when using drom globally in a project using ocaml 4.10:

```
Warning: your current environment contains a different opam switch "4.13.1", be careful.
```

My global setup is similar to the docs suggest, but updated to work with opam 2.1:

```sh
 function drom () {
    opam exec --switch=4.13.1 -- drom "$@";
  }
```

**Comment by lefessan** [comment]
Why do you do that ? Because `drom` is installed in that switch ? I would advise to use `opam install drom --destdir ~/bin/` for example, to install `drom` outside of this specific switch (well, data files will still be in that switch, but the binary will be in ~/bin, that can be added to your PATH).

**Comment by joprice** [comment]
I was just quickly following the docs to try out the tool for the first time and that method is listed as the first option for installing globally here https://ocamlpro.github.io/drom/sphinx/install.html#user-profile-shell-function. I switched to using opam install and no longer get the warning.

**Comment by Karfroth** [comment]
It seems there is another warning because `opam config exec` is deprecated in opam 2.1. 

I got this error when I used https://ocamlpro.github.io/drom/sphinx/install.html#user-profile-shell-function

```
$ drom --help
[WARNING] exec was deprecated in version 2.1 of the opam CLI. Use opam exec instead or set OPAMCLI environment variable
          to 2.0.
```

Using `opam exec` does not give this warning, so I guess the document should use it instead of `opam config exec`?
